packages:
  - packages/*
  - app/*
  - tools/*

overrides:
  typescript: 6.0.2

allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true

minimumReleaseAgeExclude:
  - eslint@10.8.0
  - '@playwright/test@1.62.0'
  - playwright-core@1.62.0
  - playwright@1.62.0

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - vue-demi
