export const RANK_DATA_TYPES = [
    'experience',
    'dedication',
    'firenum',
    'warnum',
    'killnum',
    'deathnum',
    'occupied',
    'killcrew',
    'deathcrew',
    'killcrew_person',
    'deathcrew_person',
    'dex1',
    'dex2',
    'dex3',
    'dex4',
    'dex5',
    'ttw',
    'ttd',
    'ttl',
    'ttg',
    'ttp',
    'tlw',
    'tld',
    'tll',
    'tlg',
    'tlp',
    'tsw',
    'tsd',
    'tsl',
    'tsg',
    'tsp',
    'tiw',
    'tid',
    'til',
    'tig',
    'tip',
    'betwin',
    'betgold',
    'betwingold',
    'inherit_earned',
    'inherit_spent',
] as const;

export type RankDataType = (typeof RANK_DATA_TYPES)[number];

export const HALL_OF_FAME_TYPES = [
    'experience',
    'dedication',
    'firenum',
    'warnum',
    'killnum',
    'winrate',
    'occupied',
    'killcrew',
    'killrate',
    'killcrew_person',
    'killrate_person',
    'dex1',
    'dex2',
    'dex3',
    'dex4',
    'dex5',
    'ttrate',
    'tlrate',
    'tsrate',
    'tirate',
    'betgold',
    'betwin',
    'betwingold',
    'betrate',
] as const;

export type HallOfFameType = (typeof HALL_OF_FAME_TYPES)[number];
